# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [10]:
import numpy as np

In [11]:
print(np.__version__)

2.3.3


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

By using:
- np.seterr(all='ignore') which disables all warnings. Not recommended as you will be notified of any errors
- np.seterr(all='warn') show a RuntimeWarning (default behavior) and is the default warning




#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

Not true as:
-  np.sqrt is used to get the square root of positive input elements 
-  np.emath.sqrt is used to get the square root of negative input elements which is a complex number


In [18]:
a = np.sqrt(-1)
print(f"a=",a)

a= nan


/var/folders/b7/64294z_j16d0t1nszkgct6_c0000gn/T/ipykernel_59454/2443393954.py:1: RuntimeWarning: invalid value encountered in sqrt
  a = np.sqrt(-1)


In [19]:
b = np.emath.sqrt(-1)
print(f"b=",b)

b= 1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [23]:
date = np.datetime64('2025-09-18')
print(date)

2025-09-18


In [26]:
today = np.datetime64('today','D')
print(today)

2025-09-18


In [38]:
today_timestamp = np.datetime64('today','D')
print(today_timestamp)

2025


In [30]:
now = np.datetime64('now')
print(now)

2025-09-18T10:16:43


In [39]:
yesterday = today - np.timedelta64(1,'D')
print(yesterday)

2025-09-17


In [41]:
tomorrow = today + np.timedelta64(1,'D')
print(tomorrow)

2025-09-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [48]:
july_2016 = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [60]:
A = np.arange(3,9,dtype=float).reshape(3,2)
B = np.arange(13,19,dtype=float).reshape(3,2)
np.add(A,B,out=A)
np.multiply(A,-A/B,out=A)
print(A)

[[-19.69230769 -23.14285714]
 [-26.66666667 -30.25      ]
 [-33.88235294 -37.55555556]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [71]:
c = np.arange(4.84,10.59,dtype=float).reshape(3,2)
print(c)

[[4.84 5.84]
 [6.84 7.84]
 [8.84 9.84]]


1. Using np.floor to return the nearest integer that is less than or equal to the array element.

In [72]:
np.floor(c)

array([[4., 5.],
       [6., 7.],
       [8., 9.]])

2. Using np.trunc to return the nearest integer which is closer to zero than array element is.

In [73]:
np.trunc(c)

array([[4., 5.],
       [6., 7.],
       [8., 9.]])

3. Using np.astype to return specified data type(integer), truncating the decimal part when converting to integer.

In [77]:
c.astype(int)

array([[4, 5],
       [6, 7],
       [8, 9]])

4. np.modf to return the fractional and integral parts separately

In [80]:
np.modf(c)

(array([[0.84, 0.84],
        [0.84, 0.84],
        [0.84, 0.84]]),
 array([[4., 5.],
        [6., 7.],
        [8., 9.]]))

np.int to return the default integer type

In [81]:
np.int_(c)

array([[4, 5],
       [6, 7],
       [8, 9]])

np.fix to return the nearest integer towards 0

In [82]:
np.fix(c)

array([[4., 5.],
       [6., 7.],
       [8., 9.]])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [92]:
d = np.arange(5)
print(d)


[0 1 2 3 4]


Using tiles

In [93]:
np.tile(d,(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

Using broadcasting

In [99]:
d1 = np.zeros((5,1),dtype=int)
print(d1)

[[0]
 [0]
 [0]
 [0]
 [0]]


In [101]:
d2 = d+d1
print(d2)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [117]:
def generate_int():
    for i in range(10):
        yield i

generated_int = generate_int()
e = np.array(list(generated_int))
print(e)   


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [120]:
np.linspace(0,1,12,endpoint=False)[1:]

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333,
       0.91666667])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [126]:
f = np.random.rand(10)
print(f"f=",f)
f1 = np.sort(f)
print(f"f1=",f1)

f= [0.05472062 0.30666584 0.05473842 0.83328948 0.31070799 0.97262592
 0.70089538 0.01363551 0.92871582 0.57533056]
f1= [0.01363551 0.05472062 0.05473842 0.30666584 0.31070799 0.57533056
 0.70089538 0.83328948 0.92871582 0.97262592]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)