# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [ ]:
import shutil
import os

source = "/Users/atienojacinta/Downloads/Numpy2.ipynb"

destination_folder = "/Users/atienojacinta/PYDATA /Numpy"

os.makedirs(destination_folder, exist_ok=True)

destination = os.path.join(destination_folder, "daily_practise2.ipynb")

shutil.move(source, destination)

print(f"Moved {source} ➝ {destination}")

In [238]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

Padding an array

In [5]:
#padding with zero
a = np.array([1,2,3])
np.pad(a,(2,3))

array([0, 0, 1, 2, 3, 0, 0, 0])

In [11]:
#padding with constant mode: adds fixed constant values
b = np.array([[1,2,3],[4,5,6]])
np.pad(b,(1,2),mode='constant',constant_values=(8,9))

array([[8, 8, 8, 8, 9, 9],
       [8, 1, 2, 3, 9, 9],
       [8, 4, 5, 6, 9, 9],
       [8, 9, 9, 9, 9, 9],
       [8, 9, 9, 9, 9, 9]])

In [14]:
#padding with edge: repeats the edge values of the array.
c = np.array([[1,2,3],[4,5,6]])
np.pad(c,(1,2),mode='edge')

array([[1, 1, 2, 3, 3, 3],
       [1, 1, 2, 3, 3, 3],
       [4, 4, 5, 6, 6, 6],
       [4, 4, 5, 6, 6, 6],
       [4, 4, 5, 6, 6, 6]])

In [16]:
#padding with reflect: mirrors the array without repeating the edge element.
d = np.array([[1,2,3],[4,5,6]])
np.pad(d,(1,2),mode='reflect')

array([[5, 4, 5, 6, 5, 4],
       [2, 1, 2, 3, 2, 1],
       [5, 4, 5, 6, 5, 4],
       [2, 1, 2, 3, 2, 1],
       [5, 4, 5, 6, 5, 4]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [27]:
e = (1,2,3,4)
f = np.diag(e,k=-1)
print(f)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [39]:
g = (1,2,3,4)
h = np.zeros((5,5),dtype=int)
np.fill_diagonal(h[1:],g)
print(h)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

Using Indices

In [42]:
i = np.indices((8,8))
print(i)

[[[0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3 3]
  [4 4 4 4 4 4 4 4]
  [5 5 5 5 5 5 5 5]
  [6 6 6 6 6 6 6 6]
  [7 7 7 7 7 7 7 7]]

 [[0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]]]


In [43]:
j = i.sum(axis=0)
print(j)

[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]]


In [45]:
k = j%2
print(k)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Using Slicing

In [54]:
l = np.zeros((8,8),dtype=int)
l[1::2,::2]=1
l[::2,1::2]=1
print(l)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [57]:
m = np.arange(6*7*8).reshape(6,7,8)
n = 99
o = np.unravel_index(n,m.shape)
print(o)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [60]:
p = np.array([[0,1],[0,1]])
q = np.tile(p,(4,4))
print(q)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [70]:
#normalize is to scale down to values between 0 and 1
r = np.random.randint(low=3,high=8,size=(5,5),dtype=int)
print(r)

[[3 5 4 7 5]
 [3 4 7 4 5]
 [6 7 6 3 4]
 [7 7 5 3 4]
 [7 3 3 5 5]]


In [71]:
r_min = r.min()
r_max = r.max()
r_normal = (r-r_min)/(r_max-r_min)
print(r_normal)

[[0.   0.5  0.25 1.   0.5 ]
 [0.   0.25 1.   0.25 0.5 ]
 [0.75 1.   0.75 0.   0.25]
 [1.   1.   0.5  0.   0.25]
 [1.   0.   0.   0.5  0.5 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [79]:
colour = np.dtype([('R',np.uint8),('B',np.uint8),('G',np.uint8),('A',np.uint8)])
print(colour)

[('R', 'u1'), ('B', 'u1'), ('G', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [104]:
s1 = np.arange(16,31).reshape(5,3)
print(f"s1:", s1)
s2 = np.arange(2,8).reshape(3,2)
print(f"s2:", s2)
s3 = np.dot(s1,s2)
print(s3)

s1: [[16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]
S2: [[2 3]
 [4 5]
 [6 7]]
[[208 259]
 [244 304]
 [280 349]
 [316 394]
 [352 439]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [116]:
t = np.arange(1,10)
print(t)
t[(t>3)&(t<8)] *=-1
print(t)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [126]:
print(sum(range(5),-1))

#this is still giving 10 because numoy was already installed but when running from a file without numpy,
# it uses the built i python sum() function and adds the numbers iteratively starting with the one defined in the function

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [127]:
z = np.array([1,2,3,4],dtype=int)
print(z)

[1 2 3 4]


In [128]:
z1 = z**z
print(z1)

#allowed

[  1   4  27 256]


In [129]:
z2 = 2<<z>>2
print(z2)
#allowed

[1 2 4 8]


In [130]:
z3 = z<-z
print(z3)

#allowed 

#< is used to represent less than np.less
# for <-, python intepretes the - as -z thus z<(-z)
#it therefore compares the elements of z with their negatives, and returns True or False 
# depending whether the lement is less than it's negative

[False False False False]


In [132]:
z4 = 1j*z
print(z4)

#allowed
#1j is a type of imaginary nuber that automatically turns an array into a complex array with a real part and an imaginary part


[0.+1.j 0.+2.j 0.+3.j 0.+4.j]


In [135]:
z5 = z/1/1
print(z5)

#allowed
#z/1/1 divides z by 1 and agin by 1 gicing the result of a float instead of an integer as the operator / automatically converts tghe int to a float

[1. 2. 3. 4.]


In [136]:
z6 = z<z>z
print(z6)

#not allowed as numpy does not allow wide comparison but has to be split into element-wise operations combined with logical operators as below

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [137]:
z7 = (z<z)&(z>z)
print(z7)

[False False False False]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [138]:
np.array(0) / np.array(0)


/var/folders/b7/64294z_j16d0t1nszkgct6_c0000gn/T/ipykernel_43903/3272234849.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [139]:
np.array(0) // np.array(0)


/var/folders/b7/64294z_j16d0t1nszkgct6_c0000gn/T/ipykernel_43903/474058805.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [140]:
np.array([np.nan]).astype(int).astype(float)

/var/folders/b7/64294z_j16d0t1nszkgct6_c0000gn/T/ipykernel_43903/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

#### 29. How to round away from zero a float array ? (★☆☆)

In [174]:
a1 = np.arange(3.5462,14.9864).reshape(3,4)
print(a1)

[[ 3.5462  4.5462  5.5462  6.5462]
 [ 7.5462  8.5462  9.5462 10.5462]
 [11.5462 12.5462 13.5462 14.5462]]


In [175]:
a2 = np.round(a1,2)
print(a2)

[[ 3.55  4.55  5.55  6.55]
 [ 7.55  8.55  9.55 10.55]
 [11.55 12.55 13.55 14.55]]


In [178]:
a3 = np.around(a1)
print(a3)

[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [196]:
a4 = np.arange(-5.5481,6.3476).reshape(4,3)
print(a4)

[[-5.5481 -4.5481 -3.5481]
 [-2.5481 -1.5481 -0.5481]
 [ 0.4519  1.4519  2.4519]
 [ 3.4519  4.4519  5.4519]]


In [199]:
#uses absilute to be able to make every object positive and enable round off to the higher next number
a5 = abs(a4)
print(a5)

[[5.5481 4.5481 3.5481]
 [2.5481 1.5481 0.5481]
 [0.4519 1.4519 2.4519]
 [3.4519 4.4519 5.4519]]


In [201]:
#use ceil to round to the next higher float
a6 = np.ceil(a5)
print(a6)

[[6. 5. 4.]
 [3. 2. 1.]
 [1. 2. 3.]
 [4. 5. 6.]]


In [203]:
#use copysign to return the original sign after rounding is done
a7 = np.copysign(a6,a4)
print(a7)

[[-6. -5. -4.]
 [-3. -2. -1.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]]


In [205]:
#one line code to do all the round away from zero
a8 = np.copysign(np.ceil(abs(a4)),a4)
print(a8)

[[-6. -5. -4.]
 [-3. -2. -1.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]]


#### 30. How to find common values between two arrays? (★☆☆)

In [236]:
b1 = np.arange(3,15).reshape(3,4)
b2 = np.arange(4,10).reshape(3,2)
print(b1)
print(b2)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[4 5]
 [6 7]
 [8 9]]


In [237]:
b3 = np.intersect1d(b1,b2)
print(b3)

[4 5 6 7 8 9]
