# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
(np.__version__)

'2.3.3'

3.Create a null vector of size 10 (★☆☆)

In [8]:
null_vector = np.zeros(10)
print(null_vector)
print(type(null_vector))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


#### 4. How to find the memory size of any array (★☆☆)

In [15]:
print(null_vector.nbytes)
print(null_vector.itemsize)

80
8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

pydoc3 numpy.add 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [19]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [21]:
b = np.linspace(10,49)
print(b)

[10.         10.79591837 11.59183673 12.3877551  13.18367347 13.97959184
 14.7755102  15.57142857 16.36734694 17.16326531 17.95918367 18.75510204
 19.55102041 20.34693878 21.14285714 21.93877551 22.73469388 23.53061224
 24.32653061 25.12244898 25.91836735 26.71428571 27.51020408 28.30612245
 29.10204082 29.89795918 30.69387755 31.48979592 32.28571429 33.08163265
 33.87755102 34.67346939 35.46938776 36.26530612 37.06122449 37.85714286
 38.65306122 39.44897959 40.24489796 41.04081633 41.83673469 42.63265306
 43.42857143 44.2244898  45.02040816 45.81632653 46.6122449  47.40816327
 48.20408163 49.        ]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
c = b[::-1]
print(c)

[49.         48.20408163 47.40816327 46.6122449  45.81632653 45.02040816
 44.2244898  43.42857143 42.63265306 41.83673469 41.04081633 40.24489796
 39.44897959 38.65306122 37.85714286 37.06122449 36.26530612 35.46938776
 34.67346939 33.87755102 33.08163265 32.28571429 31.48979592 30.69387755
 29.89795918 29.10204082 28.30612245 27.51020408 26.71428571 25.91836735
 25.12244898 24.32653061 23.53061224 22.73469388 21.93877551 21.14285714
 20.34693878 19.55102041 18.75510204 17.95918367 17.16326531 16.36734694
 15.57142857 14.7755102  13.97959184 13.18367347 12.3877551  11.59183673
 10.79591837 10.        ]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [26]:
d = np.reshape(np.arange(0,9),(3,3))
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [28]:
e = np.array([1,2,0,0,4,0])
g = np.nonzero(e)
print(g)
print(g[0])


(array([0, 1, 4]),)
[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [29]:
h = np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [40]:
j = np.random.randint(low=0, high=14, size=(3,3), dtype=int)
print(j)
print(type(j))

[[ 9  6  2]
 [13  7  2]
 [ 0  1 12]]
<class 'numpy.ndarray'>


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [41]:
k = np.random.randint(low=12, high=111, size=(10,10), dtype=int)
print(k)

[[ 99  24  53  82  39  73  39  97  55  37]
 [ 54 104  64  53  73  97  29  88  73  80]
 [ 69  73  45  49  74  71  50  43  29  14]
 [103  85  12 102  58  55  36  33  13 108]
 [105  30  83 102  51  76  27  73  31  42]
 [ 72 101  40  19  60  52  29  82  99 107]
 [ 61  56  29  27  75  66  87 103  59  74]
 [ 31  13  20  33  37  35  52  19  24 100]
 [ 93  86 107  45  55  95  19  45  90  40]
 [ 23  28  51  82  48  32 109  32  89  14]]


In [45]:
print(k.min())
print(k.max())

12
109


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [49]:
l = np.random.random(30)
print(l)

[0.39792785 0.09287317 0.39043743 0.15925708 0.4557071  0.91349057
 0.34464305 0.95071625 0.93988661 0.31540427 0.08621593 0.95563642
 0.0118296  0.06285201 0.81109623 0.85623101 0.74581487 0.64431839
 0.79880743 0.73211912 0.00276261 0.54771482 0.69418543 0.60070303
 0.11594114 0.15044541 0.15034235 0.4627916  0.99024654 0.10183085]


In [50]:
print(l.mean())

0.482740939596995


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [52]:
m = np.ones((7,7),dtype=int)
m[1:-1,1:-1]=0
print(m)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]
