# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [ ]:
import shutil
import os

source = "/Users/atienojacinta/Downloads/Numpy2.ipynb"

destination_folder = "/Users/atienojacinta/PYDATA /Numpy"

os.makedirs(destination_folder, exist_ok=True)

destination = os.path.join(destination_folder, "daily_practise2.ipynb")

shutil.move(source, destination)

print(f"Moved {source} ➝ {destination}")

In [4]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

Padding an array

In [5]:
#padding with zero
a = np.array([1,2,3])
np.pad(a,(2,3))

array([0, 0, 1, 2, 3, 0, 0, 0])

In [11]:
#padding with constant mode: adds fixed constant values
b = np.array([[1,2,3],[4,5,6]])
np.pad(b,(1,2),mode='constant',constant_values=(8,9))

array([[8, 8, 8, 8, 9, 9],
       [8, 1, 2, 3, 9, 9],
       [8, 4, 5, 6, 9, 9],
       [8, 9, 9, 9, 9, 9],
       [8, 9, 9, 9, 9, 9]])

In [14]:
#padding with edge: repeats the edge values of the array.
c = np.array([[1,2,3],[4,5,6]])
np.pad(c,(1,2),mode='edge')

array([[1, 1, 2, 3, 3, 3],
       [1, 1, 2, 3, 3, 3],
       [4, 4, 5, 6, 6, 6],
       [4, 4, 5, 6, 6, 6],
       [4, 4, 5, 6, 6, 6]])

In [16]:
#padding with reflect: mirrors the array without repeating the edge element.
d = np.array([[1,2,3],[4,5,6]])
np.pad(d,(1,2),mode='reflect')

array([[5, 4, 5, 6, 5, 4],
       [2, 1, 2, 3, 2, 1],
       [5, 4, 5, 6, 5, 4],
       [2, 1, 2, 3, 2, 1],
       [5, 4, 5, 6, 5, 4]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [27]:
e = (1,2,3,4)
f = np.diag(e,k=-1)
print(f)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [39]:
g = (1,2,3,4)
h = np.zeros((5,5),dtype=int)
np.fill_diagonal(h[1:],g)
print(h)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

Using Indices

In [42]:
i = np.indices((8,8))
print(i)

[[[0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3 3]
  [4 4 4 4 4 4 4 4]
  [5 5 5 5 5 5 5 5]
  [6 6 6 6 6 6 6 6]
  [7 7 7 7 7 7 7 7]]

 [[0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]]]


In [43]:
j = i.sum(axis=0)
print(j)

[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]]


In [45]:
k = j%2
print(k)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Using Slicing

In [54]:
l = np.zeros((8,8),dtype=int)
l[1::2,::2]=1
l[::2,1::2]=1
print(l)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [57]:
m = np.arange(6*7*8).reshape(6,7,8)
n = 99
o = np.unravel_index(n,m.shape)
print(o)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [60]:
p = np.array([[0,1],[0,1]])
q = np.tile(p,(4,4))
print(q)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [69]:
#normalize is to scale down to values between 0 and 1
r = np.random.randint(low=3,high=8,size=(5,5),dtype=int)
r_min = r.min()
r_max = r.max()
r_normal = (r-r_min)/(r_max-r_min)
print(r_normal)

[[0.25 0.   0.25 1.   0.25]
 [0.75 0.5  0.75 0.   0.  ]
 [0.5  0.25 0.75 0.75 0.5 ]
 [0.   1.   0.75 0.   0.75]
 [0.25 1.   0.75 0.75 1.  ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)