In [3]:
import numpy as np

In [4]:
print(np.__version__)

2.3.3


In [5]:
a = [1,2,3,4,5,6]
print(type(a))

<class 'list'>


In [6]:
np.array(a)

array([1, 2, 3, 4, 5, 6])

In [7]:
b = np.array(a)
print(type(b))

<class 'numpy.ndarray'>


In [9]:
print(a)
print(b)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [102]:
c = np.array([2,3,4,5])
print(c)
print(type(c))

[2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
d = np.arange(6)
print(d)
print(type(d))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
e = np.arange(4.5)
print(e)
print(type(e))

[0. 1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [14]:
f = np.array(["Dorice", "loves", "numpy"])
print(f)
print(type(f))

['Dorice' 'loves' 'numpy']
<class 'numpy.ndarray'>


In [15]:
print(np.ones(3))

[1. 1. 1.]


In [21]:
print(np.ones(3,dtype=int))

[1 1 1]


In [22]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [23]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.zeros((5,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [28]:
np.linspace(0,5,2)

array([0., 5.])

In [29]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [30]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [37]:
np.linspace(start=50,stop=200,num=7)

array([ 50.,  75., 100., 125., 150., 175., 200.])

In [38]:
np.linspace(start=50,stop=200)

array([ 50.        ,  53.06122449,  56.12244898,  59.18367347,
        62.24489796,  65.30612245,  68.36734694,  71.42857143,
        74.48979592,  77.55102041,  80.6122449 ,  83.67346939,
        86.73469388,  89.79591837,  92.85714286,  95.91836735,
        98.97959184, 102.04081633, 105.10204082, 108.16326531,
       111.2244898 , 114.28571429, 117.34693878, 120.40816327,
       123.46938776, 126.53061224, 129.59183673, 132.65306122,
       135.71428571, 138.7755102 , 141.83673469, 144.89795918,
       147.95918367, 151.02040816, 154.08163265, 157.14285714,
       160.20408163, 163.26530612, 166.32653061, 169.3877551 ,
       172.44897959, 175.51020408, 178.57142857, 181.63265306,
       184.69387755, 187.75510204, 190.81632653, 193.87755102,
       196.93877551, 200.        ])

In [39]:
np.linspace(start=50,stop=200,endpoint=False,dtype=int)

array([ 50,  53,  56,  59,  62,  65,  68,  71,  74,  77,  80,  83,  86,
        89,  92,  95,  98, 101, 104, 107, 110, 113, 116, 119, 122, 125,
       128, 131, 134, 137, 140, 143, 146, 149, 152, 155, 158, 161, 164,
       167, 170, 173, 176, 179, 182, 185, 188, 191, 194, 197])

In [41]:
np.full(shape=(7,6),fill_value=12,dtype=int)

array([[12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12]])

In [47]:
np.random.random(4)

array([0.10565454, 0.65376516, 0.90364314, 0.12621436])

In [50]:
np.random.random(4)

array([0.0762734 , 0.66647819, 0.17113836, 0.56253729])

In [57]:
np.random.randint(low=52,high=75,size=3,dtype=int)

array([72, 63, 72])

In [63]:
np.random.randint(low=52,high=75,size=(4,8),dtype=int)

array([[70, 63, 56, 52, 55, 65, 53, 58],
       [63, 57, 60, 65, 58, 66, 66, 71],
       [54, 60, 54, 53, 65, 63, 58, 67],
       [57, 58, 52, 60, 61, 56, 52, 74]])

In [66]:
#loc=mean, scale= sd, size=
np.random.normal(loc = 5,scale=2.7, size=7)

array([7.90694351, 5.58605579, 6.79710762, 4.09300197, 5.19443776,
       4.87500594, 5.66370274])

In [68]:
#eye/identity matrix = diagonal values are similar
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [110]:
g = np.array([[[[1,2,3,4],[5,6,7,8],[9,10,1,2]]]])
print(g)
print(type(g))

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10  1  2]]]]
<class 'numpy.ndarray'>


In [111]:
#ndim show the #of dimensions in the array
g.ndim

4

In [113]:
# size gives the #of elements
g.size

12

In [114]:
#shape gives the #of rows and columns
g.shape

(1, 1, 3, 4)

In [122]:
import os

source = "/Users/atienojacinta/Downloads/Numpy1 (2).ipynb"
print(os.path.exists(source))


True


In [124]:
import os

downloads = "/Users/atienojacinta/Downloads"

for f in os.listdir(downloads):
    if f.endswith(".ipynb"):
        print(f)


Numpy1 (2) (2).ipynb
Numpy1 (2) (1).ipynb
Numpy1 (2).ipynb


In [125]:
import os, shutil

# Paths
source = "/Users/atienojacinta/Downloads/Numpy1 (2).ipynb"
destination_folder = "Numpy"
destination = os.path.join(destination_folder, "Numpy1 (2).ipynb")

# Ensure destination folder exists
os.makedirs(destination_folder, exist_ok=True)

# Move file
shutil.move(source, destination)

print(f"Moved '{source}' ➝ '{destination}'")


Moved '/Users/atienojacinta/Downloads/Numpy1 (2).ipynb' ➝ 'Numpy/Numpy1 (2).ipynb'
