In [2]:
import numpy as np

In [4]:
a = np.array([[[1,2,3,4],[9,8,7,6]]])
print(a.ndim)
print(a)

3
[[[1 2 3 4]
  [9 8 7 6]]]


In [5]:
print(a.shape)
print(a.size)

(1, 2, 4)
8


In [7]:
b = a.reshape(1,8)
print(b)

[[1 2 3 4 9 8 7 6]]


In [10]:
c = a.reshape(2,4)
print(c)

[[1 2 3 4]
 [9 8 7 6]]


In [12]:
d = np.array([2,3,4])
e = np.array([6,7,8])

In [13]:
np.concatenate((d,e),axis=0)

array([2, 3, 4, 6, 7, 8])

In [19]:
g = np.array([[2,3,4]])
h = np.array([[6,7,8]])

In [21]:
np.concatenate((g,h),axis=1)

array([[2, 3, 4, 6, 7, 8]])

In [ ]:
np.concatenate((g,h),axis=0)

array([[2, 3, 4],
       [6, 7, 8]])

In [24]:
i = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(i.ndim)
print(i)

3
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [26]:
i.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Vectorization

In [27]:
j = np.array([[2,3,4]])
k = np.array([[6,7,8]])

In [28]:
j+k

array([[ 8, 10, 12]])

In [29]:
g+20

array([[22, 23, 24]])