In [1]:
import numpy as np

In [ ]:
import shutil
import os

source = "/Users/atienojacinta/Downloads/day3.ipynb"

destination_folder = "/Users/atienojacinta/PYDATA /Numpy"

os.makedirs(destination_folder, exist_ok=True)

destination = os.path.join(destination_folder, "day3.ipynb")

shutil.move(source, destination)

print(f"Moved {source} ➝ {destination}")

In [3]:
x = np.array([2,1,4,3,7,6])

In [4]:
# sorting arrays

np.sort(x)

array([1, 2, 3, 4, 6, 7])

In [5]:
a = np.array([[34,12,11],[2,9,5],[6,3,8]])
print(a)

[[34 12 11]
 [ 2  9  5]
 [ 6  3  8]]


In [ ]:
# axis =1
# last axis = -1
# Multidimensional array (3d what's the last axis, how does this differ from 1)

np.sort(a,axis=-1)

array([[11, 12, 34],
       [ 2,  5,  9],
       [ 3,  6,  8]])

In [23]:
np.sort(a,axis=None)[::-1]

array([34, 12, 11,  9,  8,  6,  5,  3,  2])

In [26]:
np.sort(a,axis=1)

array([[11, 12, 34],
       [ 2,  5,  9],
       [ 3,  6,  8]])

Argsort

In [27]:
x =  np.array([4,1,6,3,7])

4 ; 0
1; 1
6 ; 2
3 : 3
7 : 4

In [28]:
np.sort(x)

array([1, 3, 4, 6, 7])

In [29]:
np.argsort(x)

array([1, 3, 0, 2, 4])

Partition

In [ ]:
# the k smallest value in an array

In [58]:
arr = np.array([3,7,9,1,9,8])


In [63]:
# 3 smallest elements in an array

np.partition(arr,2)

array([1, 3, 7, 8, 9, 9])

In [74]:
arr2 = np.array([72,54,33,89,56,80])

In [75]:
np.sort(arr2)

array([33, 54, 56, 72, 80, 89])

In [ ]:
index 2 ; 56
index 4 ; 80

In [76]:
np.partition(arr2,(2,4))

array([33, 54, 56, 72, 80, 89])

Along a specific axis

In [132]:
# random state ; (42)

rand = np.random.RandomState(42)

x = rand.randint(0,10, (4,6))
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [97]:
np.partition(x,3,axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]], dtype=int32)

In [103]:
np.partition(x,1,axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]], dtype=int32)

Basic Math Operations

In [110]:
arr1 = np.random.rand(10)
arr2 = np.random.rand(10)

In [111]:
arr1

array([0.98466638, 0.22413737, 0.39574481, 0.60970417, 0.18599604,
       0.9510972 , 0.56743324, 0.33385245, 0.71052076, 0.77775922])

In [112]:
arr2

array([0.3592932 , 0.8631237 , 0.4076891 , 0.092373  , 0.18259903,
       0.32885506, 0.24771166, 0.07308964, 0.98495903, 0.41909911])

In [113]:
np.add(arr1,arr2)

array([1.34395958, 1.08726107, 0.80343391, 0.70207717, 0.36859507,
       1.27995227, 0.81514491, 0.40694209, 1.69547979, 1.19685833])

In [115]:
np.divide(arr2,arr1)

array([0.36488825, 3.85086921, 1.03018178, 0.15150463, 0.98173607,
       0.34576389, 0.43654768, 0.21892798, 1.38624947, 0.53885457])

In [118]:
np.subtract(arr1,arr2)

array([ 0.62537319, -0.63898633, -0.01194428,  0.51733116,  0.00339702,
        0.62224214,  0.31972158,  0.26076281, -0.27443826,  0.35866011])

In [121]:
np.multiply(arr1,arr2)

array([0.35378393, 0.19345828, 0.16134084, 0.0563202 , 0.0339627 ,
       0.31277313, 0.14055983, 0.02440116, 0.69983384, 0.3259582 ])

In [122]:
np.sqrt(25)

np.float64(5.0)

In [123]:
np.abs(-2)

np.int64(2)

In [124]:
np.power(3,2)

np.int64(9)

In [125]:
np.log(100)

np.float64(4.605170185988092)

In [126]:
np.log10(100)

np.float64(2.0)

In [129]:
a = np.array([-1.7,-1.5,0.2,2.4,2.6])

In [130]:
np.floor(a)

array([-2., -2.,  0.,  2.,  2.])

In [131]:
np.ceil(a)

array([-1., -1.,  1.,  3.,  3.])

Accessing elements within an array

In [ ]:
a[r,c]

In [135]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]])

In [136]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [140]:
a[0,1]

np.int64(2)

In [145]:
a[:,2]

array([ 3, 10, 17])

In [146]:
a[2,:]

array([15, 16, 17, 18, 19, 20, 21])

In [148]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [147]:
a[:,:4]

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11],
       [15, 16, 17, 18]])

In [149]:
a[:,1:4]

array([[ 2,  3,  4],
       [ 9, 10, 11],
       [16, 17, 18]])

In [150]:
a[:2,:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [152]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [151]:
a[1:2,2:5]

array([[10, 11, 12]])

In [ ]:
# start index, end index , step size

a[1,0:-3:2]

array([ 8, 10])

: 