# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [14]:
a = np.array([3,7,8,9,15])
given_value=12

In [15]:
dif = np.abs(a-given_value)
index_min = dif.argmin()


In [16]:
closest_value = a[index_min]
print(closest_value)

9


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [35]:
a1 = np.arange(1,4).reshape(1,3)
a2 = np.arange(4,7).reshape(3,1)
print(f"a1=",a1)
print(f"a2=",a2)

a1= [[1 2 3]]
a2= [[4]
 [5]
 [6]]


In [33]:
print(f"length of a1 is",len(a1))
print(f"length of a2 is",len(a2))

length of a1 is 1
length of a2 is 3


In [38]:
a3 = np.empty((3,3))

iterator = np.nditer(a3,flags=['multi_index'],op_flags=['writeonly'])

for i in iterator:
    x,y = iterator.multi_index
    i[...] = a1[0,y]+a2[x,0]

print(a3)

[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [80]:
class ArraywithName(np.ndarray):
    def __new__(cls,input_array,name="Zindua"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self,obj):
        if obj is None: 
            return
        self.name = getattr(obj,'name',"Zindua")

    def __repr__(self):
        return f"{self.name}:{np.array(self)}"

b1 = ArraywithName([1,2,3],name="Zindua")       

In [81]:
b1

Zindua:[1 2 3]

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [84]:
v1 = np.arange(10)
print(v1)
v2 = np.array([0,1,2,3,4,4,6,3,7])
print(v2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 4 6 3 7]


In [85]:
np.add.at(v1,v2,1)

In [86]:
v1

array([1, 2, 3, 5, 6, 5, 7, 8, 8, 9])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [112]:
x = np.array([3,7,4,2,8,6])
i = np.array([0,4,6,2,3,4])
f = np.zeros(max(i)+1)

In [113]:
np.add.at(f,i,x)

In [114]:
f

array([ 3.,  0.,  2.,  8., 13.,  0.,  4.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [120]:
img = np.random.randint(0,256,(2,2,3),dtype=np.uint8)
print(img)

[[[213 163 137]
  [155 125  40]]

 [[ 71 181 206]
  [ 40  51 112]]]


In [121]:
pixels = img.reshape(-1,3)

In [122]:
pixels_view = pixels.view([('', pixels.dtype)] * 3)

In [123]:
num_colors = np.unique(pixels_view).size
print(f"Number of unique colors: {num_colors}")

Number of unique colors: 4


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [128]:
g = np.arange(0,256).reshape(4,4,4,4)
print(g)

[[[[  0   1   2   3]
   [  4   5   6   7]
   [  8   9  10  11]
   [ 12  13  14  15]]

  [[ 16  17  18  19]
   [ 20  21  22  23]
   [ 24  25  26  27]
   [ 28  29  30  31]]

  [[ 32  33  34  35]
   [ 36  37  38  39]
   [ 40  41  42  43]
   [ 44  45  46  47]]

  [[ 48  49  50  51]
   [ 52  53  54  55]
   [ 56  57  58  59]
   [ 60  61  62  63]]]


 [[[ 64  65  66  67]
   [ 68  69  70  71]
   [ 72  73  74  75]
   [ 76  77  78  79]]

  [[ 80  81  82  83]
   [ 84  85  86  87]
   [ 88  89  90  91]
   [ 92  93  94  95]]

  [[ 96  97  98  99]
   [100 101 102 103]
   [104 105 106 107]
   [108 109 110 111]]

  [[112 113 114 115]
   [116 117 118 119]
   [120 121 122 123]
   [124 125 126 127]]]


 [[[128 129 130 131]
   [132 133 134 135]
   [136 137 138 139]
   [140 141 142 143]]

  [[144 145 146 147]
   [148 149 150 151]
   [152 153 154 155]
   [156 157 158 159]]

  [[160 161 162 163]
   [164 165 166 167]
   [168 169 170 171]
   [172 173 174 175]]

  [[176 177 178 179]
   [180 181 182 183]
   [184 

In [129]:
g1 = np.sum(g,axis=(2,3))

In [130]:
g1.shape

(4, 4)

In [131]:
g1

array([[ 120,  376,  632,  888],
       [1144, 1400, 1656, 1912],
       [2168, 2424, 2680, 2936],
       [3192, 3448, 3704, 3960]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [149]:
d = np.array([1, 2, 3, 4, 5, 6])
s = np.array([0, 0, 1, 1, 1, 2]) 

In [150]:
sum_per_subset = np.bincount(s, weights=d)
count_per_subset = np.bincount(s)
mean_per_subset = sum_per_subset / count_per_subset

In [151]:
mean_per_subset

array([1.5, 4. , 6. ])

#### 69. How to get the diagonal of a dot product? (★★★)

In [133]:
h1 = np.arange(1, 10).reshape(3,3)
h2 = np.arange(10, 19).reshape(3,3)

In [134]:
h3 = np.diag(np.dot(h1,h2))

In [135]:
h3

array([ 84, 216, 366])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [137]:
i1 = np.array([1,2,3,4,5])

In [142]:
n = len(i1)

In [144]:
#3 0s between each value equals to 3*4=12 new 0s added
new_len = n + 3*(n-1)

In [145]:
new_len

17

In [147]:
i2 = np.zeros(new_len,dtype=int)
print(i2)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [148]:
# the original values take index 0,4,8,,12,16
i2[::4] = i1
print(i2)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)